<a href="https://colab.research.google.com/github/UDICatNCHU/PyTorch-SocialNetwork/blob/master/Boston_Housing_Logisitic_Regression_social_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Linear Regression with NN Framework



In [0]:
from sklearn.datasets import load_boston
boston = load_boston()

In [3]:
print(boston["data"][0])
print(boston["target"][0])

[6.320e-03 1.800e+01 2.310e+00 0.000e+00 5.380e-01 6.575e+00 6.520e+01
 4.090e+00 1.000e+00 2.960e+02 1.530e+01 3.969e+02 4.980e+00]
24.0


In [4]:
len(boston["data"])

506

In [5]:
boston["data"].shape

(506, 13)

In [6]:
boston["target"].shape

(506,)

In [0]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [8]:
from sklearn.datasets import load_boston
boston = load_boston()
print(boston.keys())

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])


In [9]:
print(boston["feature_names"])

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [0]:
x = boston["data"]

In [0]:
y = boston["target"]

In [0]:
training_data = torch.tensor(x, dtype = torch.float)
label = torch.tensor(y, dtype = torch.float)

In [13]:
training_data.shape

torch.Size([506, 13])

In [0]:
feature_dim = 13
output_dim = 1

In [0]:
class MyNet(torch.nn.Module):
    def __init__(self, n_feature, output):
        super(MyNet, self).__init__()
        self.predict = torch.nn.Linear(n_feature, output)   # output layer

    def forward(self, x):
        x = self.predict(x)             # linear output
        return x
      
net = MyNet(feature_dim, output_dim)

In [16]:
for i in net.parameters():
  print(i)

Parameter containing:
tensor([[ 0.1726,  0.0306,  0.0023,  0.1481, -0.0178, -0.1494, -0.2425, -0.0588,
          0.1648, -0.0243, -0.0887,  0.0603, -0.0849]], requires_grad=True)
Parameter containing:
tensor([-0.1212], requires_grad=True)


In [0]:
# optimizer = torch.optim.Adam(net.parameters(), lr=0.1)
optimizer = torch.optim.SGD(net.parameters(), lr=0.000001)
# criterion = torch.nn.MSELoss(reduction='mean')  # this is for regression mean squared loss

In [18]:
num_epochs = 10

for epoch in range(num_epochs):
  optimizer.zero_grad()
  outputs = net(training_data)
  loss = nn.functional.mse_loss(label.view(-1,1), outputs)
#   loss = criterion (label.view(-1,1), outputs)
  loss.backward()
  optimizer.step()
  print('Epoch {}'.format(epoch+1), "loss: ", loss.item())

Epoch 1 loss:  955.5916748046875
Epoch 2 loss:  241.7339324951172
Epoch 3 loss:  141.6963348388672
Epoch 4 loss:  127.51142883300781
Epoch 5 loss:  125.34294891357422
Epoch 6 loss:  124.86406707763672
Epoch 7 loss:  124.62979125976562
Epoch 8 loss:  124.43730163574219
Epoch 9 loss:  124.25758361816406
Epoch 10 loss:  124.08589935302734


# Hand-Crafted Linear Regression

In [0]:
training_data = torch.tensor(x, dtype = torch.float)
label = torch.tensor(y, dtype = torch.float)

In [98]:
training_data.shape

torch.Size([506, 13])

In [99]:
label.shape

torch.Size([506])

In [100]:
training_data[0]

tensor([6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01, 6.5750e+00,
        6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02,
        4.9800e+00])

In [101]:
training_data[0].shape

torch.Size([13])

In [0]:
parameters = torch.rand_like(training_data[0].view(-1,1), requires_grad=True)

In [103]:
parameters

tensor([[0.4236],
        [0.4322],
        [0.1960],
        [0.8796],
        [0.3518],
        [0.6381],
        [0.8844],
        [0.1853],
        [0.2790],
        [0.3726],
        [0.1732],
        [0.4192],
        [0.6765]], requires_grad=True)

In [104]:
training_data[0]

tensor([6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01, 6.5750e+00,
        6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02,
        4.9800e+00])

In [105]:
training_data[0].view(1,-1).shape

torch.Size([1, 13])

In [106]:
torch.mm(training_data[0].view(1,-1),parameters)

tensor([[354.0222]], grad_fn=<MmBackward>)

In [0]:
# label.view(-1,1)

In [108]:
for i in range(10):
  loss = nn.functional.mse_loss(label.view(-1,1), torch.mm(training_data, parameters))
  print("loss",loss)
  loss.backward()
  parameters.data = parameters.data - parameters.grad*0.000001
  parameters.grad.data.zero_()
  
#   parameters = parameters.clone().detach().requires_grad_(True)
#   parameters = torch.tensor(parameters)

loss tensor(141305.6719, grad_fn=<MeanBackward0>)
loss tensor(20209.3066, grad_fn=<MeanBackward0>)
loss tensor(3272.7361, grad_fn=<MeanBackward0>)
loss tensor(902.9620, grad_fn=<MeanBackward0>)
loss tensor(570.3896, grad_fn=<MeanBackward0>)
loss tensor(522.7528, grad_fn=<MeanBackward0>)
loss tensor(514.9949, grad_fn=<MeanBackward0>)
loss tensor(512.8420, grad_fn=<MeanBackward0>)
loss tensor(511.4987, grad_fn=<MeanBackward0>)
loss tensor(510.2919, grad_fn=<MeanBackward0>)


In [28]:
parameters

tensor([[ 0.0755],
        [ 0.7870],
        [ 0.4462],
        [ 0.2657],
        [ 0.7335],
        [ 0.4920],
        [ 0.4947],
        [ 0.9326],
        [ 0.1946],
        [-0.0639],
        [ 0.5517],
        [ 0.0758],
        [ 0.1102]], requires_grad=True)