<a href="https://colab.research.google.com/github/UDICatNCHU/PyTorch-SocialNetwork/blob/master/PyTorch_Exercise%E7%B7%B4%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Given a Toy Dataset

In [0]:
import numpy as np

In [0]:
x_values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [250]:
# Convert to numpy
x_train = np.array(x_values, dtype=np.float32)
x_train.shape

(11,)

In [251]:
# IMPORTANT: 2D required
x_train = x_train.reshape(-1, 1)
x_train.shape

(11, 1)

In [0]:
y_values = [1.2, 5.2, 9.2, 13.2, 17.2, 21.2, 25.2, 29.2, 33.2, 37.2, 41.2]

In [256]:
y_train = np.array(y_values, dtype=np.float32)
y_train.shape

(11,)

In [257]:
# IMPORTANT: 2D required
y_train = y_train.reshape(-1, 1)
y_train.shape
y_train

array([[ 1.2],
       [ 5.2],
       [ 9.2],
       [13.2],
       [17.2],
       [21.2],
       [25.2],
       [29.2],
       [33.2],
       [37.2],
       [41.2]], dtype=float32)

### Building Model

**Critical Imports**

In [0]:
import torch
import torch.nn as nn

**Create Model**
1. Linear model
    - True Equation: $y = wx + b$
2. Forward
    - Example
        - Input $x = 1 $
        - Output $\hat y = ?$

In [0]:
# Create class
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out

In [0]:
input_dim = 1
output_dim = 1
model = LinearRegressionModel(input_dim, output_dim)

In [0]:
learning_rate = 0.001
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [0]:
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[-0.1442]], requires_grad=True)
Parameter containing:
tensor([-0.4141], requires_grad=True)


In [0]:
epochs = 100
for epoch in range(epochs):
    epoch += 1
    # Convert numpy array to torch Variable
    #inputs = torch.from_numpy(x_train)
    inputs = torch.tensor(x_train)
    labels = torch.tensor(y_train)

    # Clear gradients w.r.t. parameters
    optimizer.zero_grad() 
    
    # Forward to get output
    outputs = model(inputs)
    
    # Calculate Loss
    loss = criterion(outputs, labels)
    
    # Getting gradients w.r.t. parameters
    loss.backward()
    
    # Updating parameters
    optimizer.step()
    
    print('epoch {}, loss {}'.format(epoch, loss.item()))

In [0]:
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[4.1331]], requires_grad=True)
Parameter containing:
tensor([0.2573], requires_grad=True)


**Compare Data**

PyTorch Framework Overview

Step 1: Define Network/Model Structure

Step 2: Instantiate Network 

Step 3: Define Loss Function

Step 4: Choose Optimizer for Gradient Update

Step 5: Train Model by finding Optimial Parameters

**Summary**

In [0]:
import torch
import torch.nn as nn

'''
STEP 1: Network Structure
'''
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out

'''
STEP 2: INSTANTIATE MODEL CLASS
'''
input_dim = ?
output_dim = ?
model = LinearRegressionModel(input_dim, output_dim)

'''
STEP 3: INSTANTIATE LOSS CLASS
'''

criterion = nn.MSELoss()

'''
STEP 4: INSTANTIATE OPTIMIZER CLASS
'''

learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

'''
STEP 5: TRAIN THE MODEL
'''
epochs = 100
for epoch in range(epochs):
    epoch += 1
    # Convert numpy array to torch tensor
    inputs = #?
    labels = #?

    # Clear gradients w.r.t. parameters
    optimizer.zero_grad() 
    
    # Forward to get output
    outputs = model(inputs)
    
    # Calculate Loss
    loss = criterion(outputs, labels)
    
    # Getting gradients w.r.t. parameters
    loss.backward()
    
    # Updating parameters
    optimizer.step()